LAB_DESCRIPTION="Firewall + DMZ - Defense in Depth"
LAB_VERSION=1.0
LAB_AUTHOR="Pedro"

r0[0]=wan
r0[1]=link_r0_fw

fw[0]=link_r0_fw
fw[1]=lan
fw[2]=dmz
fw[3]=mgmt

pc1[0]=lan
pc2[0]=lan

web[0]=dmz
dns[0]=dmz

adm[0]=mgmt